version: 2

models:
  - name: stg_local_bike__brands
    description: "Brand reference table."
    columns:
      - name: brand_id
        tests:
          - unique
          - not_null
      - name: brand_name

  - name: stg_local_bike__categories
    description: "Product category reference table."
    columns:
      - name: category_id
        tests:
          - unique
          - not_null
      - name: category_name

  - name: stg_local_bike__products
    description: "Product catalog with key attributes."
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: product_name
      - name: brand_id
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_local_bike__products
              arguments:
                to: ref('stg_local_bike__brands')
                field: brand_id
      - name: category_id
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_local_bike__products
              arguments:
                to: ref('stg_local_bike__categories')
                field: category_id
      - name: model_year
      - name: list_price
        tests:
          - dbt_utils.expression_is_true:
              name: chk_products_list_price_not_negative
              arguments:
                expression: "list_price >= 0"
  - name: stg_local_bike__stores
    description: "Store (point of sale) reference."
    columns:
      - name: store_id
        tests:
          - unique
          - not_null
      - name: store_name
      - name: city
      - name: state
      - name: zip_code

  - name: stg_local_bike__staffs
    description: "Employees (sales/ops staff)."
    columns:
      - name: staff_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone
      - name: active
      - name: store_id
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike__staffs
              arguments:
                to: ref('stg_local_bike__stores')
                field: store_id
      - name: manager_id

  - name: stg_local_bike__customers
    description: "End-customer reference."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: phone
      - name: email
      - name: street
      - name: city
      - name: state
      - name: zip_code

  - name: stg_local_bike__orders
    description: "Order headers."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_local_bike__orders
              arguments:
                to: ref('stg_local_bike__customers')
                field: customer_id
      - name: order_status
      - name: order_date
        tests:
          - not_null
      - name: required_date
      - name: shipped_date_raw
      - name: shipped_date
      - name: store_id
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike__orders
              arguments:
                to: ref('stg_local_bike__stores')
                field: store_id
      - name: staff_id
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_local_bike__orders
              arguments:
                to: ref('stg_local_bike__staffs')
                field: staff_id
  - name: stg_local_bike__order_items
    description: "Order line items."
    columns:
      - name: order_id
        tests:
          - not_null
          - relationships:
              name: order_id_foreign_key_in_stg_local_bike__order_items
              arguments:
                to: ref('stg_local_bike__orders')
                field: order_id
      - name: item_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__order_items
              arguments:
                to: ref('stg_local_bike__products')
                field: product_id
      - name: quantity
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              name: chk_order_items_quantity_positive
              arguments:
                expression: "quantity > 0"
      - name: list_price
        tests:
          - dbt_utils.expression_is_true:
              name: chk_order_items_list_price_non_negative
              arguments:
                expression: "list_price >= 0"
      - name: discount
        tests:
          - dbt_utils.expression_is_true:
              name: chk_order_items_discount_non_negative
              arguments:
                expression: "discount >= 0"
  - name: stg_local_bike__stocks
    description: "Inventory by product and store."
    columns:
      - name: store_id
        tests:
          - not_null
          - relationships:
              name: store_id_foreign_key_in_stg_local_bike__stocks
              arguments:
                to: ref('stg_local_bike__stores')
                field: store_id
      - name: product_id
        tests:
          - not_null
          - relationships:
              name: product_id_foreign_key_in_stg_local_bike__stocks
              arguments:
                to: ref('stg_local_bike__products')
                field: product_id
      - name: quantity