select
  order_id,
  item_id,
  customer_id,
  store_id,
  staff_id,
  product_id,
  order_date,
  required_date,
  shipped_date,
  order_status,
  product_name,
  model_year,
  category_name,
  brand_name,
  store_name,
  store_city,
  store_state,
  store_zip_code,
  staff_first_name,
  staff_last_name,
  staff_email,
  quantity,
  line_list_price,
  line_discount,
  gross_amount,
  round(net_amount,2) as net_amount
from {{ ref('int_local_bike__order_item') }}
